"""This module contains global constants."""

LOGGER_NAME = 'odfuzz'
MONGODB_NAME = 'odfuzz'
MONGODB_COLLECTION = 'entities'

CLIENT = 'sap-client=500'
FORMAT = '$format=json'

ENV_USERNAME = 'SAP_USERNAME'
ENV_PASSWORD = 'SAP_PASSWORD'

EXCLUDE = 'Exclude'
INCLUDE = 'Include'
SEARCH = 'SEARCH'
TOP = 'TOP'
SKIP = 'SKIP'
FILTER = 'FILTER'
GLOBAL_ENTITY = '$E_ALL$'
GLOBAL_FUNCTION = '$F_ALL$'

QUERY_OPTIONS = [FILTER, SEARCH, TOP, SKIP]

STRING_FUNC_PROB = 0.70
MATH_FUNC_PROB = 0.15
DATE_FUNC_PROB = 0.15
FUNCTION_WEIGHT = 0.3
SINGLE_VALUE_PROB = 0.2

LOGICAL_OPERATORS = {'and': 0.5, 'or': 0.5}
BOOLEAN_OPERATORS = {'eq': 0.5, 'ne': 0.5}
EXPRESSION_OPERATORS = {'eq': 0.3, 'ne': 0.3, 'gt': 0.1, 'ge': 0.1, 'lt': 0.1, 'le': 0.1}

SEED_POPULATION = 20
RECURSION_LIMIT = 3
POOL_SIZE = 10
